### ISSUE TITLE
Data is out of date

### ISSUE THREAD

**Issue by kunashir** [musa11971/iata-aircraft-codes#1]
Good data but it's a littel bit out if date. I cannot find `Sukhoi Superjet 100-95`
Did you think about adding ICAO codes?

**Comment by musa11971** [comment]
Hi Kunashir. Thanks for bringing this to my attention. I've done some research and it turns out that the aircraft you mentioned doesn't have an IATA code. ([source](https://en.wikipedia.org/wiki/List_of_ICAO_aircraft_type_designators))

Upon your request I did create a similar resource that contains most (if not all) ICAO aircraft codes. You can find it [here](https://github.com/musa11971/icao-aircraft-codes ).

Thanks for submitting the issue.

**Comment by kunashir** [comment]
According [here](http://www.avcodes.co.uk/acrtypes.asp) it aircraft has IATA code (but I use SuperJet only how indicator for completeness of data). If I have been found good source I am going to make PR.
Thanks.
